version: "3.8"

services:
  logibase:
    image: logibase
    container_name: logibase
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
    ports:
      - 8080:8080
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/management/health" ]
      interval: 5s
      timeout: 5s
      retries: 40
    expose:
      - "8080"
    networks:
      - default

  webapp:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: webapp
    command: [ "sh", "-c", "echo Built" ]  # Chỉ build, không chạy server
    volumes:
      - frontend_build:/usr/share/nginx/html
    networks:
      - default

  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      - logibase
      - webapp
    ports:
      - "80:80"
    volumes:
      - frontend_build:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - default

volumes:
  frontend_build:

networks:
  default:
    name: logibase-net



